#! /bin/sh
# /etc/init.d/telegraphy
#

# Some things that run always
# touch /var/lock/blah

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting Telegraphy"
    /usr/bin/nodejs /home/pi/telegraphy/node/server.js
    ;;
  stop)
    echo "Stopping Telegraphy"
    ;;
  *)
    echo "Usage: /etc/init.d/blah {start|stop}"
    exit 1
    ;;
esac

exit 0