#! /bin/sh
# /etc/init.d/telegraphy
#

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting Telegraphy"
    su - pi -c "forever start /home/pi/telegraphy/node/server.js"
    ;;
  stop)
    echo "Stopping Telegraphy"
    su - pi -c "forever stop /home/pi/telegraphy/node/server.js"
    ;;
  *)
    echo "Usage: /etc/init.d/telegraphy {start|stop}"
    exit 1
    ;;
esac

exit 0